export const technologies = [
  { id: 111, name: "React JS", icon: "/images/tech/react.png" },
  { id: 112, name: "Redux Toolkit", icon: "/images/tech/redux.png" },
  { id: 113, name: "JavaScript", icon: "/images/tech/javascript.png" },
  { id: 114, name: "TypeScript", icon: "/images/tech/typescript.png" },
  { id: 115, name: "Node JS", icon: "/images/tech/nodejs.png" },
  { id: 116, name: "HTML 5", icon: "/images/tech/html.png" },
  { id: 117, name: "Tailwind CSS", icon: "/images/tech/tailwind.png" },
  { id: 118, name: "CSS 3", icon: "/images/tech/css.png" },
  { id: 119, name: "Git", icon: "/images/tech/git.png" },
  { id: 110, name: "Docker", icon: "/images/tech/docker.png" },
];

export const experiences = [
  {
    id: 1,
    title: "Senior Engineering Lead",
    company: "Peristent Systems (Client- Wayfair)",
    logo: "/images/companies/persistent.png",
    iconBg: "#FFF",
    date: "Feb 2023 - December 2023",
    points: [
      "Created an in-house web application that allows the client to configure A/B testing and access corresponding reports all within a single interface.",
      "Designed the UI with React, Typescript, and Sass based on Figma mocks",
      "Collaborated with the US team for tech discussions and code reviews",
      "Established reusable components for code efficiency and future maintenance",
      "Implemented unit tests for stability and bug reduction",
      "Provided mentorship to junior team members, conducted code reviews, and offered guidance and support to help them grow and improve",
    ],
  },
  {
    id: 2,
    title: "Associate",
    company: "MSCI (Morgan Stanley Capital International)",
    logo: "/images/companies/msci.png",
    iconBg: "#FFF",
    date: "July 2021 — November 2022",
    points: [
      "Transitioned older web applications to Microfrontends using React JS, Typescript, Nx and Sass",
      "Developed APIs for the frontend with Java Spring Boot",
      "Oversaw Azure deployment, release management, and PR validation pipelines",
      "Deployed the app by containerizing it with Docker and running it on a Kubernetes Cluster",
      "Utilized d3.js to create various charts and graphs for different indices",
    ],
  },
  {
    id: 3,
    title: "Senior Associate Technology",
    company: "Synechron (Client- HSBC)",
    iconBg: "#FFF",
    logo: "/images/companies/synechron.png",
    date: "November 2019 — July 2021",
    points: [
      "Transformed HSBC's outdated Trade Finance application into a contemporary web app with React JS, Redux, and Node JS",
      "Established and maintained a shared component library using Storybook, utilized company-wide",
      "Addressed performance challenges in the live application",
      "Conducted triage sessions with the CGI backend and HSBC China's testing teams",
      "Managed deployments across various environments via Jenkins",
      "Rectified Sonar and Whitesource vulnerabilities",
      "Contributed to test case creation, elevating test coverage to over 90%",
    ],
  },
  {
    id: 4,
    title: "Senior Consultant",
    company: "Alchemy Techsol (Client- Allstate)",
    iconBg: "#FFF",
    logo: "/images/companies/alchemy.jpg",
    date: "March 2019 — November 2019",
    points: [
      "Created a web application tailored for car dealers throughout the United States, utilizing React JS, Redux, and Bootstrap",
      "Designed it responsively for cross-device compatibility with minimal adjustments",
      "Constructed backend APIs with .NET Core to retrieve data from Microsoft SQL Server",
      "Incorporated download options for data in Excel and PDF formats",
      "Authored stored procedures for retrieving insurance product rates",
    ],
  },
  {
    id: 5,
    title: "Associate Consultant",
    company: "Capgemini",
    iconBg: "#FFF",
    logo: "/images/companies/capgemini.png",
    date: "April 2016 — March 2019",
    points: [
      "Contributed to the development of web APIs for the system using .NET Core",
      "Deployed these APIs to Azure AppService and conducted thorough testing using tools such as Postman and Swagger,as well as authoring unit test cases",
      "Designed the entire application's user interface (using WPF), integrating various tools and accelerators to enhance delivery speed within an agile development model",
      "For specific submodules, I applied the MVVM (Model-View-ViewModel) architectural pattern",
      "Focused on a module for quick code generation from templates. Additionally, I leveraged Service Fabric to construct a microservices-based application, with the UI developed using React JS",
      "Participated in a hackathon in 2018, where I crafted a winning dashboard app using React JS, securing second place",
      "Completed a 3-month training program in Java development, during which I created the UI using Spring and Angular.js",
      "I also contributed to a cart management module and received training in Blueprism Automation Software",
    ],
  },
];
